export class Cliente{
    nombre:string
    identidicacion:number
    telefono:number
    correo_electronico:string
    direccion:string
    constructor(
        nombre:string,
        identidicacion:number,
        telefono:number,
        correo_electronico:string,
        direccion:string
    ){
        this.nombre=nombre
        this.identidicacion=identidicacion
        this.telefono=telefono
        this.correo_electronico=correo_electronico
        this.direccion=direccion
    }
}