"use strict";
let bookTitle = "TypeScript Basics";
let libraryName = "My Library";
let numberOfBooks = 250;
let isLibratyOpen = true;
let titulo;
let autor;
let genero;
let idioma;
let precio;
let formato;
let isbn;
let descripcion;
let estado;
let ubicacion;
let fecha_publicacion;
let editorial;
let paginas;
let dimensiones;
let peso;
let disponible;
